set(_AMENT_PACKAGE_NAME "GraphSLAM")
set(GraphSLAM_VERSION "0.0.1")
set(GraphSLAM_MAINTAINER "chuil <chuil@example.com>")
set(GraphSLAM_BUILD_DEPENDS "rclcpp" "sensor_msgs" "geometry_msgs" "tf2" "tf2_ros")
set(GraphSLAM_BUILDTOOL_DEPENDS "ament_cmake")
set(GraphSLAM_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "geometry_msgs" "tf2" "tf2_ros")
set(GraphSLAM_BUILDTOOL_EXPORT_DEPENDS )
set(GraphSLAM_EXEC_DEPENDS "rclcpp" "sensor_msgs" "geometry_msgs" "tf2" "tf2_ros")
set(GraphSLAM_TEST_DEPENDS )
set(GraphSLAM_GROUP_DEPENDS )
set(GraphSLAM_MEMBER_OF_GROUPS )
set(GraphSLAM_DEPRECATED "")
set(GraphSLAM_EXPORT_TAGS)
list(APPEND GraphSLAM_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
